deploy_prod:
  stage: deploy
  script:
    - jekyll build --destination /var/www/staticsites/codeforheilbronn-de 
  tags:
    - shell
  only:
    - master

deploy_test:
  stage: deploy
  script:
    - jekyll build --destination /var/www/staticsites/test-codeforheilbronn-de 
  tags:
    - shell