sass:
    sass_dir: styles
    style: compressed
  
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projekte
    output: true
