title: Code for Heilbronn e.V.
description: >-
  Offene Werkstatt - Open Data - Software- und Hardware Workshops

logo: /uploads/CodeForHeilbronn.svg
theme: alembic-jekyll-theme
lang: de-DE
timezone: Europe/Berlin
permalink: /:year/:month/:day/:title.html


markdown: kramdown

collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projekte
    output: true
  badges:
    title: Badges
    output: true
  events:
    title: Events
    output: true


navigation_header:
  Blog: /
  Verein: /vereine
  Projekte: /projekte
  Termine: /termine

plugins:
  - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
   - .idea/
